### ISSUE TITLE
C/C++ aren't here

### ISSUE THREAD

**Issue by gorenbk** [cdaringe/programming-language-selector#3]
**Is your feature request related to a problem? Please describe.**
C and C++ aren't in this.

**Describe the solution you'd like**
You should add C/C++ to the spreadsheet.

**Describe alternatives you've considered**
There aren't many alternatives, but I guess I could take recommendations for Rust.

**Additional context**
I checked the spreadsheet, and C/C++ aren't in it.

Thank you for this, I really love this project.

**Comment by cdaringe** [comment]
Ya, definitely need these in there. Same with c and f sharp

**Comment by cdaringe** [comment]
c & c++ added. i didn't do a _deep_ scan of how well they were modeled in all domains, but smoke checked a few (like Desktop Applications, thinking about QT, wxwidgets, etc), and it seems to be doin ok. my C is probably a bit more _off_ than my cpp assessement
